import type { MultiSelectItem } from "~/app/components/multiselect";

export type Option = MultiSelectItem & { offset?: number };

export const TIME_ZONE_OPTIONS: Option[] = [
  {
    label: "Pacific, Midway",
    value: "Pacific/Midway",
    group: "UTC-11",
    offset: -11,
    keywords: ["SST", "Samoa Standard Time"],
  },
  {
    label: "Pacific, Niue",
    value: "Pacific/Niue",
    group: "UTC-11",
    offset: -11,
    keywords: ["NUT", "Niue Time"],
  },
  {
    label: "Pacific, Pago Pago",
    value: "Pacific/Pago_Pago",
    group: "UTC-11",
    offset: -11,
    keywords: ["SST", "Samoa Standard Time"],
  },
  {
    label: "Pacific, Honolulu",
    value: "Pacific/Honolulu",
    group: "UTC-10",
    offset: -10,
    keywords: ["HST", "Hawaii Standard Time"],
  },
  {
    label: "Pacific, Johnston",
    value: "Pacific/Johnston",
    group: "UTC-10",
    offset: -10,
    keywords: ["HST", "Hawaii Standard Time"],
  },
  {
    label: "Pacific, Rarotonga",
    value: "Pacific/Rarotonga",
    group: "UTC-10",
    offset: -10,
    keywords: ["CKT", "Cook Islands Time"],
  },
  {
    label: "Pacific, Tahiti",
    value: "Pacific/Tahiti",
    group: "UTC-10",
    offset: -10,
    keywords: ["TAHT", "Tahiti Time"],
  },
  {
    label: "Pacific, Marquesas",
    value: "Pacific/Marquesas",
    group: "UTC-09:30",
    offset: -9.5,
    keywords: ["MART", "Marquesas Time"],
  },
  {
    label: "America, Adak",
    value: "America/Adak",
    group: "UTC-09",
    offset: -9,
    keywords: ["HAST", "Hawaii-Aleutian Standard Time"],
  },
  {
    label: "Pacific, Gambier",
    value: "Pacific/Gambier",
    group: "UTC-09",
    offset: -9,
    keywords: ["GAMT", "Gambier Time"],
  },
  {
    label: "America, Anchorage",
    value: "America/Anchorage",
    group: "UTC-08",
    offset: -8,
    keywords: ["AKST", "Alaska Standard Time"],
  },
  {
    label: "America, Juneau",
    value: "America/Juneau",
    group: "UTC-08",
    offset: -8,
    keywords: ["AKST", "Alaska Standard Time"],
  },
  {
    label: "America, Metlakatla",
    value: "America/Metlakatla",
    group: "UTC-08",
    offset: -8,
    keywords: ["AKST", "Alaska Standard Time"],
  },
  {
    label: "America, Nome",
    value: "America/Nome",
    group: "UTC-08",
    offset: -8,
    keywords: ["AKST", "Alaska Standard Time"],
  },
  {
    label: "America, Sitka",
    value: "America/Sitka",
    group: "UTC-08",
    offset: -8,
    keywords: ["AKST", "Alaska Standard Time"],
  },
  {
    label: "America, Yakutat",
    value: "America/Yakutat",
    group: "UTC-08",
    offset: -8,
    keywords: ["AKST", "Alaska Standard Time"],
  },
  {
    label: "Pacific, Pitcairn",
    value: "Pacific/Pitcairn",
    group: "UTC-08",
    offset: -8,
    keywords: ["PST", "Pitcairn Standard Time"],
  },
  {
    label: "America, Creston",
    value: "America/Creston",
    group: "UTC-07",
    offset: -7,
    keywords: ["MST", "Mountain Standard Time"],
  },
  {
    label: "America, Dawson",
    value: "America/Dawson",
    group: "UTC-07",
    offset: -7,
    keywords: ["MST", "Mountain Standard Time"],
  },
  {
    label: "America, Dawson Creek",
    value: "America/Dawson_Creek",
    group: "UTC-07",
    offset: -7,
    keywords: ["MST", "Mountain Standard Time"],
  },
  {
    label: "America, Fort Nelson",
    value: "America/Fort_Nelson",
    group: "UTC-07",
    offset: -7,
    keywords: ["MST", "Mountain Standard Time"],
  },
  {
    label: "America, Hermosillo",
    value: "America/Hermosillo",
    group: "UTC-07",
    offset: -7,
    keywords: ["MST", "Mountain Standard Time"],
  },
  {
    label: "America, Los Angeles",
    value: "America/Los_Angeles",
    group: "UTC-07",
    offset: -7,
    keywords: ["PST", "Pacific Standard Time"],
  },
  {
    label: "America, Phoenix",
    value: "America/Phoenix",
    group: "UTC-07",
    offset: -7,
    keywords: ["MST", "Mountain Standard Time"],
  },
  {
    label: "America, Santa Isabel",
    value: "America/Santa_Isabel",
    group: "UTC-07",
    offset: -7,
    keywords: ["MST", "Mountain Standard Time"],
  },
  {
    label: "America, Tijuana",
    value: "America/Tijuana",
    group: "UTC-07",
    offset: -7,
    keywords: ["PST", "Pacific Standard Time"],
  },
  {
    label: "America, Vancouver",
    value: "America/Vancouver",
    group: "UTC-07",
    offset: -7,
    keywords: ["PST", "Pacific Standard Time"],
  },
  {
    label: "America, Whitehorse",
    value: "America/Whitehorse",
    group: "UTC-07",
    offset: -7,
    keywords: ["PST", "Pacific Standard Time"],
  },
  {
    label: "America, Belize",
    value: "America/Belize",
    group: "UTC-06",
    offset: -6,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Boise",
    value: "America/Boise",
    group: "UTC-06",
    offset: -6,
    keywords: ["MST", "Mountain Standard Time"],
  },
  {
    label: "America, Cambridge Bay",
    value: "America/Cambridge_Bay",
    group: "UTC-06",
    offset: -6,
    keywords: ["MST", "Mountain Standard Time"],
  },
  {
    label: "America, Chihuahua",
    value: "America/Chihuahua",
    group: "UTC-06",
    offset: -6,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Costa Rica",
    value: "America/Costa_Rica",
    group: "UTC-06",
    offset: -6,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Denver",
    value: "America/Denver",
    group: "UTC-06",
    offset: -6,
    keywords: ["MST", "Mountain Standard Time"],
  },
  {
    label: "America, Edmonton",
    value: "America/Edmonton",
    group: "UTC-06",
    offset: -6,
    keywords: ["MST", "Mountain Standard Time"],
  },
  {
    label: "America, El Salvador",
    value: "America/El_Salvador",
    group: "UTC-06",
    offset: -6,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Guatemala",
    value: "America/Guatemala",
    group: "UTC-06",
    offset: -6,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Inuvik",
    value: "America/Inuvik",
    group: "UTC-06",
    offset: -6,
    keywords: ["MST", "Mountain Standard Time"],
  },
  {
    label: "America, Managua",
    value: "America/Managua",
    group: "UTC-06",
    offset: -6,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Mazatlan",
    value: "America/Mazatlan",
    group: "UTC-06",
    offset: -6,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Ojinaga",
    value: "America/Ojinaga",
    group: "UTC-06",
    offset: -6,
    keywords: ["MST", "Mountain Standard Time"],
  },
  {
    label: "America, Regina",
    value: "America/Regina",
    group: "UTC-06",
    offset: -6,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Swift Current",
    value: "America/Swift_Current",
    group: "UTC-06",
    offset: -6,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Tegucigalpa",
    value: "America/Tegucigalpa",
    group: "UTC-06",
    offset: -6,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Yellowknife",
    value: "America/Yellowknife",
    group: "UTC-06",
    offset: -6,
    keywords: ["MST", "Mountain Standard Time"],
  },
  {
    label: "Pacific, Galapagos",
    value: "Pacific/Galapagos",
    group: "UTC-06",
    offset: -6,
    keywords: ["GALT", "Galapagos Time"],
  },
  {
    label: "America, Atikokan",
    value: "America/Atikokan",
    group: "UTC-05",
    offset: -5,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Bahia Banderas",
    value: "America/Bahia_Banderas",
    group: "UTC-05",
    offset: -5,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Bogota",
    value: "America/Bogota",
    group: "UTC-05",
    offset: -5,
    keywords: ["COT", "Colombia Time"],
  },
  {
    label: "America, Cancun",
    value: "America/Cancun",
    group: "UTC-05",
    offset: -5,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Chicago",
    value: "America/Chicago",
    group: "UTC-05",
    offset: -5,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Eirunepe",
    value: "America/Eirunepe",
    group: "UTC-05",
    offset: -5,
    keywords: ["ACT", "Amazon Time"],
  },
  {
    label: "America, Guayaquil",
    value: "America/Guayaquil",
    group: "UTC-05",
    offset: -5,
    keywords: ["ECT", "Ecuador Time"],
  },
  {
    label: "America, Indiana Knox",
    value: "America/Indiana/Knox",
    group: "UTC-05",
    offset: -5,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Indiana Tell City",
    value: "America/Indiana/Tell_City",
    group: "UTC-05",
    offset: -5,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Jamaica",
    value: "America/Jamaica",
    group: "UTC-05",
    offset: -5,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Lima",
    value: "America/Lima",
    group: "UTC-05",
    offset: -5,
    keywords: ["PET", "Peru Time"],
  },
  {
    label: "America, Matamoros",
    value: "America/Matamoros",
    group: "UTC-05",
    offset: -5,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Menominee",
    value: "America/Menominee",
    group: "UTC-05",
    offset: -5,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Merida",
    value: "America/Merida",
    group: "UTC-05",
    offset: -5,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Mexico City",
    value: "America/Mexico_City",
    group: "UTC-05",
    offset: -5,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Monterrey",
    value: "America/Monterrey",
    group: "UTC-05",
    offset: -5,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, North Dakota Beulah",
    value: "America/North_Dakota/Beulah",
    group: "UTC-05",
    offset: -5,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, North Dakota Center",
    value: "America/North_Dakota/Center",
    group: "UTC-05",
    offset: -5,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, North Dakota New Salem",
    value: "America/North_Dakota/New_Salem",
    group: "UTC-05",
    offset: -5,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Panama",
    value: "America/Panama",
    group: "UTC-05",
    offset: -5,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Rainy River",
    value: "America/Rainy_River",
    group: "UTC-05",
    offset: -5,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "America, Rankin Inlet",
    value: "America/Rankin_Inlet",
    group: "UTC-05",
    offset: -5,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Resolute",
    value: "America/Resolute",
    group: "UTC-05",
    offset: -5,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Rio Branco",
    value: "America/Rio_Branco",
    group: "UTC-05",
    offset: -5,
    keywords: ["ACT", "Amazon Time"],
  },
  {
    label: "America, Winnipeg",
    value: "America/Winnipeg",
    group: "UTC-05",
    offset: -5,
    keywords: ["CST", "Central Standard Time"],
  },
  {
    label: "Pacific, Easter",
    value: "Pacific/Easter",
    group: "UTC-05",
    offset: -5,
    keywords: ["EASST", "Easter Island Summer Time"],
  },
  {
    label: "America, Caracas",
    value: "America/Caracas",
    group: "UTC-04:30",
    offset: -4.5,
    keywords: ["VET", "Venezuela Time"],
  },
  {
    label: "America, Anguilla",
    value: "America/Anguilla",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Antigua",
    value: "America/Antigua",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Aruba",
    value: "America/Aruba",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Asuncion",
    value: "America/Asuncion",
    group: "UTC-04",
    offset: -4,
    keywords: ["PYT", "Paraguay Time"],
  },
  {
    label: "America, Barbados",
    value: "America/Barbados",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Blanc-Sablon",
    value: "America/Blanc-Sablon",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Boa Vista",
    value: "America/Boa_Vista",
    group: "UTC-04",
    offset: -4,
    keywords: ["AMT", "Amazon Standard Time"],
  },
  {
    label: "America, Campo Grande",
    value: "America/Campo_Grande",
    group: "UTC-04",
    offset: -4,
    keywords: ["AMT", "Amazon Standard Time"],
  },
  {
    label: "America, Cayman",
    value: "America/Cayman",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Cuiaba",
    value: "America/Cuiaba",
    group: "UTC-04",
    offset: -4,
    keywords: ["AMT", "Amazon Standard Time"],
  },
  {
    label: "America, Curacao",
    value: "America/Curacao",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Detroit",
    value: "America/Detroit",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Dominica",
    value: "America/Dominica",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Grand Turk",
    value: "America/Grand_Turk",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Grenada",
    value: "America/Grenada",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Guadeloupe",
    value: "America/Guadeloupe",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Guyana",
    value: "America/Guyana",
    group: "UTC-04",
    offset: -4,
    keywords: ["GYT", "Guyana Time"],
  },
  {
    label: "America, Havana",
    value: "America/Havana",
    group: "UTC-04",
    offset: -4,
    keywords: ["CST", "Cuban Standard Time"],
  },
  {
    label: "America, Indiana Indianapolis",
    value: "America/Indiana/Indianapolis",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Indiana Marengo",
    value: "America/Indiana/Marengo",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Indiana Petersburg",
    value: "America/Indiana/Petersburg",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Indiana Vevay",
    value: "America/Indiana/Vevay",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Indiana Vincennes",
    value: "America/Indiana/Vincennes",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Indiana Winamac",
    value: "America/Indiana/Winamac",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Iqaluit",
    value: "America/Iqaluit",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Kentucky Louisville",
    value: "America/Kentucky/Louisville",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Kentucky Monticello",
    value: "America/Kentucky/Monticello",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Kralendijk",
    value: "America/Kralendijk",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, La Paz",
    value: "America/La_Paz",
    group: "UTC-04",
    offset: -4,
    keywords: ["BOT", "Bolivia Time"],
  },
  {
    label: "America, Lower Princes",
    value: "America/Lower_Princes",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Manaus",
    value: "America/Manaus",
    group: "UTC-04",
    offset: -4,
    keywords: ["AMT", "Amazon Standard Time"],
  },
  {
    label: "America, Marigot",
    value: "America/Marigot",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Martinique",
    value: "America/Martinique",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Montserrat",
    value: "America/Montserrat",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Nassau",
    value: "America/Nassau",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, New York",
    value: "America/New_York",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Nipigon",
    value: "America/Nipigon",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Pangnirtung",
    value: "America/Pangnirtung",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Port of Spain",
    value: "America/Port_of_Spain",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Port-au-Prince",
    value: "America/Port-au-Prince",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Porto Velho",
    value: "America/Porto_Velho",
    group: "UTC-04",
    offset: -4,
    keywords: ["AMT", "Amazon Standard Time"],
  },
  {
    label: "America, Puerto Rico",
    value: "America/Puerto_Rico",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Santo Domingo",
    value: "America/Santo_Domingo",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, St Barthelemy",
    value: "America/St_Barthelemy",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, St Kitts",
    value: "America/St_Kitts",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, St Lucia",
    value: "America/St_Lucia",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, St Thomas",
    value: "America/St_Thomas",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, St Vincent",
    value: "America/St_Vincent",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Thunder Bay",
    value: "America/Thunder_Bay",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Toronto",
    value: "America/Toronto",
    group: "UTC-04",
    offset: -4,
    keywords: ["EST", "Eastern Standard Time"],
  },
  {
    label: "America, Tortola",
    value: "America/Tortola",
    group: "UTC-04",
    offset: -4,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Araguaina",
    value: "America/Araguaina",
    group: "UTC-03",
    offset: -3,
    keywords: ["BRT", "Brasilia Standard Time"],
  },
  {
    label: "America, Argentina Buenos Aires",
    value: "America/Argentina/Buenos_Aires",
    group: "UTC-03",
    offset: -3,
    keywords: ["ART", "Argentina Time"],
  },
  {
    label: "America, Argentina Catamarca",
    value: "America/Argentina/Catamarca",
    group: "UTC-03",
    offset: -3,
    keywords: ["ART", "Argentina Time"],
  },
  {
    label: "America, Argentina Cordoba",
    value: "America/Argentina/Cordoba",
    group: "UTC-03",
    offset: -3,
    keywords: ["ART", "Argentina Time"],
  },
  {
    label: "America, Argentina Jujuy",
    value: "America/Argentina/Jujuy",
    group: "UTC-03",
    offset: -3,
    keywords: ["ART", "Argentina Time"],
  },
  {
    label: "America, Argentina La Rioja",
    value: "America/Argentina/La_Rioja",
    group: "UTC-03",
    offset: -3,
    keywords: ["ART", "Argentina Time"],
  },
  {
    label: "America, Argentina Mendoza",
    value: "America/Argentina/Mendoza",
    group: "UTC-03",
    offset: -3,
    keywords: ["ART", "Argentina Time"],
  },
  {
    label: "America, Argentina Rio Gallegos",
    value: "America/Argentina/Rio_Gallegos",
    group: "UTC-03",
    offset: -3,
    keywords: ["ART", "Argentina Time"],
  },
  {
    label: "America, Argentina Salta",
    value: "America/Argentina/Salta",
    group: "UTC-03",
    offset: -3,
    keywords: ["ART", "Argentina Time"],
  },
  {
    label: "America, Argentina San Juan",
    value: "America/Argentina/San_Juan",
    group: "UTC-03",
    offset: -3,
    keywords: ["ART", "Argentina Time"],
  },
  {
    label: "America, Argentina San Luis",
    value: "America/Argentina/San_Luis",
    group: "UTC-03",
    offset: -3,
    keywords: ["ART", "Argentina Time"],
  },
  {
    label: "America, Argentina Tucuman",
    value: "America/Argentina/Tucuman",
    group: "UTC-03",
    offset: -3,
    keywords: ["ART", "Argentina Time"],
  },
  {
    label: "America, Argentina Ushuaia",
    value: "America/Argentina/Ushuaia",
    group: "UTC-03",
    offset: -3,
    keywords: ["ART", "Argentina Time"],
  },
  {
    label: "America, Bahia",
    value: "America/Bahia",
    group: "UTC-03",
    offset: -3,
    keywords: ["BRT", "Brasilia Standard Time"],
  },
  {
    label: "America, Belem",
    value: "America/Belem",
    group: "UTC-03",
    offset: -3,
    keywords: ["BRT", "Brasilia Standard Time"],
  },
  {
    label: "America, Cayenne",
    value: "America/Cayenne",
    group: "UTC-03",
    offset: -3,
    keywords: ["GFT", "French Guiana Time"],
  },
  {
    label: "America, Fortaleza",
    value: "America/Fortaleza",
    group: "UTC-03",
    offset: -3,
    keywords: ["BRT", "Brasilia Standard Time"],
  },
  {
    label: "America, Glace Bay",
    value: "America/Glace_Bay",
    group: "UTC-03",
    offset: -3,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Goose Bay",
    value: "America/Goose_Bay",
    group: "UTC-03",
    offset: -3,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Halifax",
    value: "America/Halifax",
    group: "UTC-03",
    offset: -3,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Maceio",
    value: "America/Maceio",
    group: "UTC-03",
    offset: -3,
    keywords: ["BRT", "Brasilia Standard Time"],
  },
  {
    label: "America, Moncton",
    value: "America/Moncton",
    group: "UTC-03",
    offset: -3,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "America, Montevideo",
    value: "America/Montevideo",
    group: "UTC-03",
    offset: -3,
    keywords: ["UYT", "Uruguay Time"],
  },
  {
    label: "America, Paramaribo",
    value: "America/Paramaribo",
    group: "UTC-03",
    offset: -3,
    keywords: ["SRT", "Suriname Time"],
  },
  {
    label: "America, Recife",
    value: "America/Recife",
    group: "UTC-03",
    offset: -3,
    keywords: ["BRT", "Brasilia Standard Time"],
  },
  {
    label: "America, Santarem",
    value: "America/Santarem",
    group: "UTC-03",
    offset: -3,
    keywords: ["BRT", "Brasilia Standard Time"],
  },
  {
    label: "America, Santiago",
    value: "America/Santiago",
    group: "UTC-03",
    offset: -3,
    keywords: ["CLT", "Chile Standard Time"],
  },
  {
    label: "America, Sao Paulo",
    value: "America/Sao_Paulo",
    group: "UTC-03",
    offset: -3,
    keywords: ["BRT", "Brasilia Standard Time"],
  },
  {
    label: "America, Thule",
    value: "America/Thule",
    group: "UTC-03",
    offset: -3,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "Antarctica, Palmer",
    value: "Antarctica/Palmer",
    group: "UTC-03",
    offset: -3,
    keywords: ["CLT", "Chile Standard Time"],
  },
  {
    label: "Antarctica, Rothera",
    value: "Antarctica/Rothera",
    group: "UTC-03",
    offset: -3,
    keywords: ["ART", "Argentina Time"],
  },
  {
    label: "Atlantic, Bermuda",
    value: "Atlantic/Bermuda",
    group: "UTC-03",
    offset: -3,
    keywords: ["AST", "Atlantic Standard Time"],
  },
  {
    label: "Atlantic, Stanley",
    value: "Atlantic/Stanley",
    group: "UTC-03",
    offset: -3,
    keywords: ["FKT", "Falkland Islands Time"],
  },
  {
    label: "America, St Johns",
    value: "America/St_Johns",
    group: "UTC-02:30",
    offset: -2.5,
    keywords: ["NST", "Newfoundland Standard Time"],
  },
  {
    label: "America, Godthab",
    value: "America/Godthab",
    group: "UTC-02",
    offset: -2,
    keywords: ["WGT", "West Greenland Time"],
  },
  {
    label: "America, Miquelon",
    value: "America/Miquelon",
    group: "UTC-02",
    offset: -2,
    keywords: ["PMT", "Saint Pierre and Miquelon Time"],
  },
  {
    label: "America, Noronha",
    value: "America/Noronha",
    group: "UTC-02",
    offset: -2,
    keywords: ["FNT", "Fernando de Noronha Time"],
  },
  {
    label: "Atlantic, South Georgia",
    value: "Atlantic/South_Georgia",
    group: "UTC-02",
    offset: -2,
    keywords: ["GST", "South Georgia Time"],
  },
  {
    label: "Atlantic, Cape Verde",
    value: "Atlantic/Cape_Verde",
    group: "UTC-01",
    offset: -1,
    keywords: ["CVT", "Cape Verde Time"],
  },
  {
    label: "Africa, Abidjan",
    value: "Africa/Abidjan",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Africa, Accra",
    value: "Africa/Accra",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Africa, Bamako",
    value: "Africa/Bamako",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Africa, Banjul",
    value: "Africa/Banjul",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Africa, Bissau",
    value: "Africa/Bissau",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Africa, Casablanca",
    value: "Africa/Casablanca",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Africa, Conakry",
    value: "Africa/Conakry",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Africa, Dakar",
    value: "Africa/Dakar",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Africa, El Aaiun",
    value: "Africa/El_Aaiun",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Africa, Freetown",
    value: "Africa/Freetown",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Africa, Lome",
    value: "Africa/Lome",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Africa, Monrovia",
    value: "Africa/Monrovia",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Africa, Nouakchott",
    value: "Africa/Nouakchott",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Africa, Ouagadougou",
    value: "Africa/Ouagadougou",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Africa, Sao Tome",
    value: "Africa/Sao_Tome",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "America, Danmarkshavn",
    value: "America/Danmarkshavn",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "America, Scoresbysund",
    value: "America/Scoresbysund",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Atlantic, Azores",
    value: "Atlantic/Azores",
    group: "UTC+00",
    offset: 0,
    keywords: ["AZOST", "Azores Standard Time"],
  },
  {
    label: "Atlantic, Reykjavik",
    value: "Atlantic/Reykjavik",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "Atlantic, St Helena",
    value: "Atlantic/St_Helena",
    group: "UTC+00",
    offset: 0,
    keywords: ["GMT", "Greenwich Mean Time"],
  },
  {
    label: "UTC",
    value: "UTC",
    group: "UTC+00",
    offset: 0,
    keywords: ["UTC", "Universal Time Coordinated"],
  },
  {
    label: "Africa, Algiers",
    value: "Africa/Algiers",
    group: "UTC+01",
    offset: 1,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Africa, Bangui",
    value: "Africa/Bangui",
    group: "UTC+01",
    offset: 1,
    keywords: ["WAT", "West Africa Time"],
  },
  {
    label: "Africa, Brazzaville",
    value: "Africa/Brazzaville",
    group: "UTC+01",
    offset: 1,
    keywords: ["WAT", "West Africa Time"],
  },
  {
    label: "Africa, Douala",
    value: "Africa/Douala",
    group: "UTC+01",
    offset: 1,
    keywords: ["WAT", "West Africa Time"],
  },
  {
    label: "Africa, Kinshasa",
    value: "Africa/Kinshasa",
    group: "UTC+01",
    offset: 1,
    keywords: ["WAT", "West Africa Time"],
  },
  {
    label: "Africa, Lagos",
    value: "Africa/Lagos",
    group: "UTC+01",
    offset: 1,
    keywords: ["WAT", "West Africa Time"],
  },
  {
    label: "Africa, Libreville",
    value: "Africa/Libreville",
    group: "UTC+01",
    offset: 1,
    keywords: ["WAT", "West Africa Time"],
  },
  {
    label: "Africa, Luanda",
    value: "Africa/Luanda",
    group: "UTC+01",
    offset: 1,
    keywords: ["WAT", "West Africa Time"],
  },
  {
    label: "Africa, Malabo",
    value: "Africa/Malabo",
    group: "UTC+01",
    offset: 1,
    keywords: ["WAT", "West Africa Time"],
  },
  {
    label: "Africa, Ndjamena",
    value: "Africa/Ndjamena",
    group: "UTC+01",
    offset: 1,
    keywords: ["WAT", "West Africa Time"],
  },
  {
    label: "Africa, Niamey",
    value: "Africa/Niamey",
    group: "UTC+01",
    offset: 1,
    keywords: ["WAT", "West Africa Time"],
  },
  {
    label: "Africa, Porto-Novo",
    value: "Africa/Porto-Novo",
    group: "UTC+01",
    offset: 1,
    keywords: ["WAT", "West Africa Time"],
  },
  {
    label: "Africa, Tunis",
    value: "Africa/Tunis",
    group: "UTC+01",
    offset: 1,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Africa, Windhoek",
    value: "Africa/Windhoek",
    group: "UTC+01",
    offset: 1,
    keywords: ["WAT", "West Africa Time"],
  },
  {
    label: "Atlantic, Canary",
    value: "Atlantic/Canary",
    group: "UTC+01",
    offset: 1,
    keywords: ["WET", "Western European Time"],
  },
  {
    label: "Atlantic, Faroe",
    value: "Atlantic/Faroe",
    group: "UTC+01",
    offset: 1,
    keywords: ["WET", "Western European Time"],
  },
  {
    label: "Atlantic, Madeira",
    value: "Atlantic/Madeira",
    group: "UTC+01",
    offset: 1,
    keywords: ["WET", "Western European Time"],
  },
  {
    label: "Europe, Dublin",
    value: "Europe/Dublin",
    group: "UTC+01",
    offset: 1,
    keywords: ["IST", "Irish Standard Time"],
  },
  {
    label: "Europe, Guernsey",
    value: "Europe/Guernsey",
    group: "UTC+01",
    offset: 1,
    keywords: ["BST", "British Summer Time"],
  },
  {
    label: "Europe, Isle of Man",
    value: "Europe/Isle_of_Man",
    group: "UTC+01",
    offset: 1,
    keywords: ["BST", "British Summer Time"],
  },
  {
    label: "Europe, Jersey",
    value: "Europe/Jersey",
    group: "UTC+01",
    offset: 1,
    keywords: ["BST", "British Summer Time"],
  },
  {
    label: "Europe, Lisbon",
    value: "Europe/Lisbon",
    group: "UTC+01",
    offset: 1,
    keywords: ["WET", "Western European Time"],
  },
  {
    label: "Europe, London",
    value: "Europe/London",
    group: "UTC+01",
    offset: 1,
    keywords: ["BST", "British Summer Time"],
  },
  {
    label: "Africa, Blantyre",
    value: "Africa/Blantyre",
    group: "UTC+02",
    offset: 2,
    keywords: ["CAT", "Central Africa Time"],
  },
  {
    label: "Africa, Bujumbura",
    value: "Africa/Bujumbura",
    group: "UTC+02",
    offset: 2,
    keywords: ["CAT", "Central Africa Time"],
  },
  {
    label: "Africa, Cairo",
    value: "Africa/Cairo",
    group: "UTC+02",
    offset: 2,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Africa, Ceuta",
    value: "Africa/Ceuta",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Africa, Gaborone",
    value: "Africa/Gaborone",
    group: "UTC+02",
    offset: 2,
    keywords: ["CAT", "Central Africa Time"],
  },
  {
    label: "Africa, Harare",
    value: "Africa/Harare",
    group: "UTC+02",
    offset: 2,
    keywords: ["CAT", "Central Africa Time"],
  },
  {
    label: "Africa, Johannesburg",
    value: "Africa/Johannesburg",
    group: "UTC+02",
    offset: 2,
    keywords: ["SAST", "South Africa Standard Time"],
  },
  {
    label: "Africa, Kigali",
    value: "Africa/Kigali",
    group: "UTC+02",
    offset: 2,
    keywords: ["CAT", "Central Africa Time"],
  },
  {
    label: "Africa, Lubumbashi",
    value: "Africa/Lubumbashi",
    group: "UTC+02",
    offset: 2,
    keywords: ["CAT", "Central Africa Time"],
  },
  {
    label: "Africa, Lusaka",
    value: "Africa/Lusaka",
    group: "UTC+02",
    offset: 2,
    keywords: ["CAT", "Central Africa Time"],
  },
  {
    label: "Africa, Maputo",
    value: "Africa/Maputo",
    group: "UTC+02",
    offset: 2,
    keywords: ["CAT", "Central Africa Time"],
  },
  {
    label: "Africa, Maseru",
    value: "Africa/Maseru",
    group: "UTC+02",
    offset: 2,
    keywords: ["SAST", "South Africa Standard Time"],
  },
  {
    label: "Africa, Mbabane",
    value: "Africa/Mbabane",
    group: "UTC+02",
    offset: 2,
    keywords: ["SAST", "South Africa Standard Time"],
  },
  {
    label: "Africa, Tripoli",
    value: "Africa/Tripoli",
    group: "UTC+02",
    offset: 2,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Antarctica, Troll",
    value: "Antarctica/Troll",
    group: "UTC+02",
    offset: 2,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Arctic, Longyearbyen",
    value: "Arctic/Longyearbyen",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Amsterdam",
    value: "Europe/Amsterdam",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Andorra",
    value: "Europe/Andorra",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Belgrade",
    value: "Europe/Belgrade",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Berlin",
    value: "Europe/Berlin",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Bratislava",
    value: "Europe/Bratislava",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Brussels",
    value: "Europe/Brussels",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Budapest",
    value: "Europe/Budapest",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Busingen",
    value: "Europe/Busingen",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Copenhagen",
    value: "Europe/Copenhagen",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Gibraltar",
    value: "Europe/Gibraltar",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Kaliningrad",
    value: "Europe/Kaliningrad",
    group: "UTC+02",
    offset: 2,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Europe, Ljubljana",
    value: "Europe/Ljubljana",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Luxembourg",
    value: "Europe/Luxembourg",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Madrid",
    value: "Europe/Madrid",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Malta",
    value: "Europe/Malta",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Monaco",
    value: "Europe/Monaco",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Oslo",
    value: "Europe/Oslo",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Paris",
    value: "Europe/Paris",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Podgorica",
    value: "Europe/Podgorica",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Prague",
    value: "Europe/Prague",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Rome",
    value: "Europe/Rome",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, San Marino",
    value: "Europe/San_Marino",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Sarajevo",
    value: "Europe/Sarajevo",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Skopje",
    value: "Europe/Skopje",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Stockholm",
    value: "Europe/Stockholm",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Tirane",
    value: "Europe/Tirane",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Vaduz",
    value: "Europe/Vaduz",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Vatican",
    value: "Europe/Vatican",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Vienna",
    value: "Europe/Vienna",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Warsaw",
    value: "Europe/Warsaw",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Zagreb",
    value: "Europe/Zagreb",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Europe, Zurich",
    value: "Europe/Zurich",
    group: "UTC+02",
    offset: 2,
    keywords: ["CET", "Central European Time"],
  },
  {
    label: "Africa, Addis Ababa",
    value: "Africa/Addis_Ababa",
    group: "UTC+03",
    offset: 3,
    keywords: ["EAT", "East Africa Time"],
  },
  {
    label: "Africa, Asmara",
    value: "Africa/Asmara",
    group: "UTC+03",
    offset: 3,
    keywords: ["EAT", "East Africa Time"],
  },
  {
    label: "Africa, Dar es Salaam",
    value: "Africa/Dar_es_Salaam",
    group: "UTC+03",
    offset: 3,
    keywords: ["EAT", "East Africa Time"],
  },
  {
    label: "Africa, Djibouti",
    value: "Africa/Djibouti",
    group: "UTC+03",
    offset: 3,
    keywords: ["EAT", "East Africa Time"],
  },
  {
    label: "Africa, Juba",
    value: "Africa/Juba",
    group: "UTC+03",
    offset: 3,
    keywords: ["EAT", "East Africa Time"],
  },
  {
    label: "Africa, Kampala",
    value: "Africa/Kampala",
    group: "UTC+03",
    offset: 3,
    keywords: ["EAT", "East Africa Time"],
  },
  {
    label: "Africa, Khartoum",
    value: "Africa/Khartoum",
    group: "UTC+03",
    offset: 3,
    keywords: ["EAT", "East Africa Time"],
  },
  {
    label: "Africa, Mogadishu",
    value: "Africa/Mogadishu",
    group: "UTC+03",
    offset: 3,
    keywords: ["EAT", "East Africa Time"],
  },
  {
    label: "Africa, Nairobi",
    value: "Africa/Nairobi",
    group: "UTC+03",
    offset: 3,
    keywords: ["EAT", "East Africa Time"],
  },
  {
    label: "Antarctica, Syowa",
    value: "Antarctica/Syowa",
    group: "UTC+03",
    offset: 3,
    keywords: ["EAT", "East Africa Time"],
  },
  {
    label: "Asia, Aden",
    value: "Asia/Aden",
    group: "UTC+03",
    offset: 3,
    keywords: ["AST", "Arabia Standard Time"],
  },
  {
    label: "Asia, Amman",
    value: "Asia/Amman",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Asia, Baghdad",
    value: "Asia/Baghdad",
    group: "UTC+03",
    offset: 3,
    keywords: ["AST", "Arabia Standard Time"],
  },
  {
    label: "Asia, Bahrain",
    value: "Asia/Bahrain",
    group: "UTC+03",
    offset: 3,
    keywords: ["AST", "Arabia Standard Time"],
  },
  {
    label: "Asia, Beirut",
    value: "Asia/Beirut",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Asia, Damascus",
    value: "Asia/Damascus",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Asia, Gaza",
    value: "Asia/Gaza",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Asia, Hebron",
    value: "Asia/Hebron",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Asia, Jerusalem",
    value: "Asia/Jerusalem",
    group: "UTC+03",
    offset: 3,
    keywords: ["IST", "Israel Standard Time"],
  },
  {
    label: "Asia, Kuwait",
    value: "Asia/Kuwait",
    group: "UTC+03",
    offset: 3,
    keywords: ["AST", "Arabia Standard Time"],
  },
  {
    label: "Asia, Nicosia",
    value: "Asia/Nicosia",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Asia, Qatar",
    value: "Asia/Qatar",
    group: "UTC+03",
    offset: 3,
    keywords: ["AST", "Arabia Standard Time"],
  },
  {
    label: "Asia, Riyadh",
    value: "Asia/Riyadh",
    group: "UTC+03",
    offset: 3,
    keywords: ["AST", "Arabia Standard Time"],
  },
  {
    label: "Europe, Athens",
    value: "Europe/Athens",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Europe, Bucharest",
    value: "Europe/Bucharest",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Europe, Chisinau",
    value: "Europe/Chisinau",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Europe, Helsinki",
    value: "Europe/Helsinki",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Europe, Istanbul",
    value: "Europe/Istanbul",
    group: "UTC+03",
    offset: 3,
    keywords: ["TRT", "Turkey Time"],
  },
  {
    label: "Europe, Kiev",
    value: "Europe/Kiev",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Europe, Mariehamn",
    value: "Europe/Mariehamn",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Europe, Minsk",
    value: "Europe/Minsk",
    group: "UTC+03",
    offset: 3,
    keywords: ["FET", "Further Eastern European Time"],
  },
  {
    label: "Europe, Moscow",
    value: "Europe/Moscow",
    group: "UTC+03",
    offset: 3,
    keywords: ["MSK", "Moscow Standard Time"],
  },
  {
    label: "Europe, Riga",
    value: "Europe/Riga",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Europe, Simferopol",
    value: "Europe/Simferopol",
    group: "UTC+03",
    offset: 3,
    keywords: ["MSK", "Moscow Standard Time"],
  },
  {
    label: "Europe, Sofia",
    value: "Europe/Sofia",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Europe, Tallinn",
    value: "Europe/Tallinn",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Europe, Uzhgorod",
    value: "Europe/Uzhgorod",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Europe, Vilnius",
    value: "Europe/Vilnius",
    group: "UTC+03",
    offset: 3,
    keywords: ["EET", "Eastern European Time"],
  },
  {
    label: "Europe, Volgograd",
    value: "Europe/Volgograd",
    group: "UTC+03",
    offset: 3,
    keywords: ["MSK", "Moscow Standard Time"],
  },
  {
    label: "Europe, Zaporozhye",
    value: "Europe/Zaporozhye",
    group: "UTC+03",
    offset: 3,
    keywords: ["MSK", "Moscow Standard Time"],
  },
  {
    label: "Indian, Antananarivo",
    value: "Indian/Antananarivo",
    group: "UTC+03",
    offset: 3,
    keywords: ["EAT", "East Africa Time"],
  },
  {
    label: "Indian, Comoro",
    value: "Indian/Comoro",
    group: "UTC+03",
    offset: 3,
    keywords: ["EAT", "East Africa Time"],
  },
  {
    label: "Indian, Mayotte",
    value: "Indian/Mayotte",
    group: "UTC+03",
    offset: 3,
    keywords: ["EAT", "East Africa Time"],
  },
  {
    label: "Asia, Dubai",
    value: "Asia/Dubai",
    group: "UTC+04",
    offset: 4,
    keywords: ["GST", "Gulf Standard Time"],
  },
  {
    label: "Asia, Muscat",
    value: "Asia/Muscat",
    group: "UTC+04",
    offset: 4,
    keywords: ["GST", "Gulf Standard Time"],
  },
  {
    label: "Asia, Tbilisi",
    value: "Asia/Tbilisi",
    group: "UTC+04",
    offset: 4,
    keywords: ["GET", "Georgia Time"],
  },
  {
    label: "Asia, Yerevan",
    value: "Asia/Yerevan",
    group: "UTC+04",
    offset: 4,
    keywords: ["AMT", "Armenia Time"],
  },
  {
    label: "Europe, Samara",
    value: "Europe/Samara",
    group: "UTC+04",
    offset: 4,
    keywords: ["SAMT", "Samara Time"],
  },
  {
    label: "Indian, Mahe",
    value: "Indian/Mahe",
    group: "UTC+04",
    offset: 4,
    keywords: ["SCT", "Seychelles Time"],
  },
  {
    label: "Indian, Mauritius",
    value: "Indian/Mauritius",
    group: "UTC+04",
    offset: 4,
    keywords: ["MUT", "Mauritius Time"],
  },
  {
    label: "Indian, Reunion",
    value: "Indian/Reunion",
    group: "UTC+04",
    offset: 4,
    keywords: ["RET", "Reunion Time"],
  },
  {
    label: "Asia, Kabul",
    value: "Asia/Kabul",
    group: "UTC+04:30",
    offset: 4.5,
    keywords: ["AFT", "Afghanistan Time"],
  },
  {
    label: "Asia, Tehran",
    value: "Asia/Tehran",
    group: "UTC+04:30",
    offset: 4.5,
    keywords: ["IRST", "Iran Standard Time"],
  },
  {
    label: "Antarctica, Mawson",
    value: "Antarctica/Mawson",
    group: "UTC+05",
    offset: 5,
    keywords: ["MAWT", "Mawson Time"],
  },
  {
    label: "Asia, Aqtau",
    value: "Asia/Aqtau",
    group: "UTC+05",
    offset: 5,
    keywords: ["AQTT", "Aqtau Time"],
  },
  {
    label: "Asia, Aqtobe",
    value: "Asia/Aqtobe",
    group: "UTC+05",
    offset: 5,
    keywords: ["AQTT", "Aqtobe Time"],
  },
  {
    label: "Asia, Ashgabat",
    value: "Asia/Ashgabat",
    group: "UTC+05",
    offset: 5,
    keywords: ["TMT", "Turkmenistan Time"],
  },
  {
    label: "Asia, Baku",
    value: "Asia/Baku",
    group: "UTC+05",
    offset: 5,
    keywords: ["AZT", "Azerbaijan Time"],
  },
  {
    label: "Asia, Dushanbe",
    value: "Asia/Dushanbe",
    group: "UTC+05",
    offset: 5,
    keywords: ["TJT", "Tajikistan Time"],
  },
  {
    label: "Asia, Karachi",
    value: "Asia/Karachi",
    group: "UTC+05",
    offset: 5,
    keywords: ["PKT", "Pakistan Time"],
  },
  {
    label: "Asia, Oral",
    value: "Asia/Oral",
    group: "UTC+05",
    offset: 5,
    keywords: ["AQTT", "Aqtau Time"],
  },
  {
    label: "Asia, Samarkand",
    value: "Asia/Samarkand",
    group: "UTC+05",
    offset: 5,
    keywords: ["UZT", "Uzbekistan Time"],
  },
  {
    label: "Asia, Tashkent",
    value: "Asia/Tashkent",
    group: "UTC+05",
    offset: 5,
    keywords: ["UZT", "Uzbekistan Time"],
  },
  {
    label: "Asia, Yekaterinburg",
    value: "Asia/Yekaterinburg",
    group: "UTC+05",
    offset: 5,
    keywords: ["YEKT", "Yekaterinburg Time"],
  },
  {
    label: "Indian, Kerguelen",
    value: "Indian/Kerguelen",
    group: "UTC+05",
    offset: 5,
    keywords: ["TFT", "French Southern and Antarctic Lands Time"],
  },
  {
    label: "Indian, Maldives",
    value: "Indian/Maldives",
    group: "UTC+05",
    offset: 5,
    keywords: ["MVT", "Maldives Time"],
  },
  {
    label: "Asia, Colombo",
    value: "Asia/Colombo",
    group: "UTC+05:30",
    offset: 5.5,
    keywords: ["IST", "Indian Standard Time"],
  },
  {
    label: "Asia, Kolkata",
    value: "Asia/Kolkata",
    group: "UTC+05:30",
    offset: 5.5,
    keywords: ["IST", "Indian Standard Time"],
  },
  {
    label: "Asia, Kathmandu",
    value: "Asia/Kathmandu",
    group: "UTC+05:45",
    offset: 5.75,
    keywords: ["NPT", "Nepal Time"],
  },
  {
    label: "Antarctica, Vostok",
    value: "Antarctica/Vostok",
    group: "UTC+06",
    offset: 6,
    keywords: ["VOST", "Vostok Time"],
  },
  {
    label: "Asia, Almaty",
    value: "Asia/Almaty",
    group: "UTC+06",
    offset: 6,
    keywords: ["ALMT", "Kazakhstan Time"],
  },
  {
    label: "Asia, Bishkek",
    value: "Asia/Bishkek",
    group: "UTC+06",
    offset: 6,
    keywords: ["KGT", "Kyrgyzstan Time"],
  },
  {
    label: "Asia, Dhaka",
    value: "Asia/Dhaka",
    group: "UTC+06",
    offset: 6,
    keywords: ["BST", "Bangladesh Standard Time"],
  },
  {
    label: "Asia, Novosibirsk",
    value: "Asia/Novosibirsk",
    group: "UTC+06",
    offset: 6,
    keywords: ["NOVT", "Novosibirsk Time"],
  },
  {
    label: "Asia, Omsk",
    value: "Asia/Omsk",
    group: "UTC+06",
    offset: 6,
    keywords: ["OMST", "Omsk Time"],
  },
  {
    label: "Asia, Qyzylorda",
    value: "Asia/Qyzylorda",
    group: "UTC+06",
    offset: 6,
    keywords: ["KGT", "Kazakhstan Time"],
  },
  {
    label: "Asia, Thimphu",
    value: "Asia/Thimphu",
    group: "UTC+06",
    offset: 6,
    keywords: ["BTT", "Bhutan Time"],
  },
  {
    label: "Asia, Urumqi",
    value: "Asia/Urumqi",
    group: "UTC+06",
    offset: 6,
    keywords: ["CST", "China Standard Time"],
  },
  {
    label: "Indian, Chagos",
    value: "Indian/Chagos",
    group: "UTC+06",
    offset: 6,
    keywords: ["IOT", "Indian Ocean Territory Time"],
  },
  {
    label: "Asia, Rangoon",
    value: "Asia/Rangoon",
    group: "UTC+06:30",
    offset: 6.5,
    keywords: ["MMT", "Myanmar Time"],
  },
  {
    label: "Indian, Cocos",
    value: "Indian/Cocos",
    group: "UTC+06:30",
    offset: 6.5,
    keywords: ["CCT", "Cocos Islands Time"],
  },
  {
    label: "Antarctica, Davis",
    value: "Antarctica/Davis",
    group: "UTC+07",
    offset: 7,
    keywords: ["DAVT", "Davis Time"],
  },
  {
    label: "Asia, Bangkok",
    value: "Asia/Bangkok",
    group: "UTC+07",
    offset: 7,
    keywords: ["ICT", "Indochina Time"],
  },
  {
    label: "Asia, Ho Chi Minh",
    value: "Asia/Ho_Chi_Minh",
    group: "UTC+07",
    offset: 7,
    keywords: ["ICT", "Indochina Time"],
  },
  {
    label: "Asia, Jakarta",
    value: "Asia/Jakarta",
    group: "UTC+07",
    offset: 7,
    keywords: ["WIB", "Western Indonesia Time"],
  },
  {
    label: "Asia, Krasnoyarsk",
    value: "Asia/Krasnoyarsk",
    group: "UTC+07",
    offset: 7,
    keywords: ["KRAT", "Krasnoyarsk Time"],
  },
  {
    label: "Asia, Novokuznetsk",
    value: "Asia/Novokuznetsk",
    group: "UTC+07",
    offset: 7,
    keywords: ["KRAT", "Krasnoyarsk Time"],
  },
  {
    label: "Asia, Phnom Penh",
    value: "Asia/Phnom_Penh",
    group: "UTC+07",
    offset: 7,
    keywords: ["ICT", "Indochina Time"],
  },
  {
    label: "Asia, Pontianak",
    value: "Asia/Pontianak",
    group: "UTC+07",
    offset: 7,
    keywords: ["WIB", "Western Indonesia Time"],
  },
  {
    label: "Asia, Vientiane",
    value: "Asia/Vientiane",
    group: "UTC+07",
    offset: 7,
    keywords: ["ICT", "Indochina Time"],
  },
  {
    label: "Indian, Christmas",
    value: "Indian/Christmas",
    group: "UTC+07",
    offset: 7,
    keywords: ["CXT", "Christmas Island Time"],
  },
  {
    label: "Antarctica, Casey",
    value: "Antarctica/Casey",
    group: "UTC+08",
    offset: 8,
    keywords: ["CAST", "Casey Time"],
  },
  {
    label: "Asia, Brunei",
    value: "Asia/Brunei",
    group: "UTC+08",
    offset: 8,
    keywords: ["BNT", "Brunei Time"],
  },
  {
    label: "Asia, Chita",
    value: "Asia/Chita",
    group: "UTC+08",
    offset: 8,
    keywords: ["YAKT", "Yakutsk Time"],
  },
  {
    label: "Asia, Hong Kong",
    value: "Asia/Hong_Kong",
    group: "UTC+08",
    offset: 8,
    keywords: ["HKT", "Hong Kong Time"],
  },
  {
    label: "Asia, Hovd",
    value: "Asia/Hovd",
    group: "UTC+08",
    offset: 8,
    keywords: ["HOVT", "Hovd Time"],
  },
  {
    label: "Asia, Irkutsk",
    value: "Asia/Irkutsk",
    group: "UTC+08",
    offset: 8,
    keywords: ["IRKT", "Irkutsk Time"],
  },
  {
    label: "Asia, Kuala Lumpur",
    value: "Asia/Kuala_Lumpur",
    group: "UTC+08",
    offset: 8,
    keywords: ["MST", "Malaysia Standard Time"],
  },
  {
    label: "Asia, Kuching",
    value: "Asia/Kuching",
    group: "UTC+08",
    offset: 8,
    keywords: ["MST", "Malaysia Standard Time"],
  },
  {
    label: "Asia, Macau",
    value: "Asia/Macau",
    group: "UTC+08",
    offset: 8,
    keywords: ["MST", "Macau Standard Time"],
  },
  {
    label: "Asia, Makassar",
    value: "Asia/Makassar",
    group: "UTC+08",
    offset: 8,
    keywords: ["WITA", "Central Indonesia Time"],
  },
  {
    label: "Asia, Manila",
    value: "Asia/Manila",
    group: "UTC+08",
    offset: 8,
    keywords: ["PST", "Philippine Standard Time"],
  },
  {
    label: "Asia, Shanghai",
    value: "Asia/Shanghai",
    group: "UTC+08",
    offset: 8,
    keywords: ["CST", "China Standard Time"],
  },
  {
    label: "Asia, Singapore",
    value: "Asia/Singapore",
    group: "UTC+08",
    offset: 8,
    keywords: ["SGT", "Singapore Time"],
  },
  {
    label: "Asia, Taipei",
    value: "Asia/Taipei",
    group: "UTC+08",
    offset: 8,
    keywords: ["CST", "China Standard Time"],
  },
  {
    label: "Australia, Perth",
    value: "Australia/Perth",
    group: "UTC+08",
    offset: 8,
    keywords: ["WST", "Western Standard Time"],
  },
  {
    label: "Asia, Pyongyang",
    value: "Asia/Pyongyang",
    group: "UTC+08:30",
    offset: 8.5,
    keywords: ["KST", "Korean Standard Time"],
  },
  {
    label: "Australia, Eucla",
    value: "Australia/Eucla",
    group: "UTC+08:45",
    offset: 8.75,
    keywords: ["ACWST", "Australian Central Western Standard Time"],
  },
  {
    label: "Asia, Choibalsan",
    value: "Asia/Choibalsan",
    group: "UTC+09",
    offset: 9,
    keywords: ["CHOT", "Choibalsan Time"],
  },
  {
    label: "Asia, Dili",
    value: "Asia/Dili",
    group: "UTC+09",
    offset: 9,
    keywords: ["TLT", "East Timor Time"],
  },
  {
    label: "Asia, Jayapura",
    value: "Asia/Jayapura",
    group: "UTC+09",
    offset: 9,
    keywords: ["WIT", "Eastern Indonesia Time"],
  },
  {
    label: "Asia, Khandyga",
    value: "Asia/Khandyga",
    group: "UTC+09",
    offset: 9,
    keywords: ["YAKT", "Yakutsk Time"],
  },
  {
    label: "Asia, Seoul",
    value: "Asia/Seoul",
    group: "UTC+09",
    offset: 9,
    keywords: ["KST", "Korean Standard Time"],
  },
  {
    label: "Asia, Tokyo",
    value: "Asia/Tokyo",
    group: "UTC+09",
    offset: 9,
    keywords: ["JST", "Japan Standard Time"],
  },
  {
    label: "Asia, Ulaanbaatar",
    value: "Asia/Ulaanbaatar",
    group: "UTC+09",
    offset: 9,
    keywords: ["ULAT", "Ulaanbaatar Time"],
  },
  {
    label: "Asia, Yakutsk",
    value: "Asia/Yakutsk",
    group: "UTC+09",
    offset: 9,
    keywords: ["YAKT", "Yakutsk Time"],
  },
  {
    label: "Pacific, Palau",
    value: "Pacific/Palau",
    group: "UTC+09",
    offset: 9,
    keywords: ["PWT", "Palau Time"],
  },
  {
    label: "Australia, Adelaide",
    value: "Australia/Adelaide",
    group: "UTC+09:30",
    offset: 9.5,
    keywords: ["ACST", "Australian Central Standard Time"],
  },
  {
    label: "Australia, Broken Hill",
    value: "Australia/Broken_Hill",
    group: "UTC+09:30",
    offset: 9.5,
    keywords: ["ACST", "Australian Central Standard Time"],
  },
  {
    label: "Australia, Darwin",
    value: "Australia/Darwin",
    group: "UTC+09:30",
    offset: 9.5,
    keywords: ["ACST", "Australian Central Standard Time"],
  },
  {
    label: "Antarctica, DumontDUrville",
    value: "Antarctica/DumontDUrville",
    group: "UTC+10",
    offset: 10,
    keywords: ["DDUT", "Dumont d'Urville Time"],
  },
  {
    label: "Asia, Magadan",
    value: "Asia/Magadan",
    group: "UTC+10",
    offset: 10,
    keywords: ["MAGT", "Magadan Time"],
  },
  {
    label: "Asia, Sakhalin",
    value: "Asia/Sakhalin",
    group: "UTC+10",
    offset: 10,
    keywords: ["SAKT", "Sakhalin Time"],
  },
  {
    label: "Asia, Ust-Nera",
    value: "Asia/Ust-Nera",
    group: "UTC+10",
    offset: 10,
    keywords: ["VLAT", "Vladivostok Time"],
  },
  {
    label: "Asia, Vladivostok",
    value: "Asia/Vladivostok",
    group: "UTC+10",
    offset: 10,
    keywords: ["VLAT", "Vladivostok Time"],
  },
  {
    label: "Australia, Brisbane",
    value: "Australia/Brisbane",
    group: "UTC+10",
    offset: 10,
    keywords: ["AEST", "Australian Eastern Standard Time"],
  },
  {
    label: "Australia, Currie",
    value: "Australia/Currie",
    group: "UTC+10",
    offset: 10,
    keywords: ["AEST", "Australian Eastern Standard Time"],
  },
  {
    label: "Australia, Hobart",
    value: "Australia/Hobart",
    group: "UTC+10",
    offset: 10,
    keywords: ["AEST", "Australian Eastern Standard Time"],
  },
  {
    label: "Australia, Lindeman",
    value: "Australia/Lindeman",
    group: "UTC+10",
    offset: 10,
    keywords: ["AEST", "Australian Eastern Standard Time"],
  },
  {
    label: "Australia, Melbourne",
    value: "Australia/Melbourne",
    group: "UTC+10",
    offset: 10,
    keywords: ["AEST", "Australian Eastern Standard Time"],
  },
  {
    label: "Australia, Sydney",
    value: "Australia/Sydney",
    group: "UTC+10",
    offset: 10,
    keywords: ["AEST", "Australian Eastern Standard Time"],
  },
  {
    label: "Pacific, Chuuk",
    value: "Pacific/Chuuk",
    group: "UTC+10",
    offset: 10,
    keywords: ["CHUT", "Chuuk Time"],
  },
  {
    label: "Pacific, Guam",
    value: "Pacific/Guam",
    group: "UTC+10",
    offset: 10,
    keywords: ["GST", "Guam Standard Time"],
  },
  {
    label: "Pacific, Port Moresby",
    value: "Pacific/Port_Moresby",
    group: "UTC+10",
    offset: 10,
    keywords: ["PGT", "Papua New Guinea Time"],
  },
  {
    label: "Pacific, Saipan",
    value: "Pacific/Saipan",
    group: "UTC+10",
    offset: 10,
    keywords: ["GST", "Guam Standard Time"],
  },
  {
    label: "Australia, Lord Howe",
    value: "Australia/Lord_Howe",
    group: "UTC+10:30",
    offset: 10.5,
    keywords: ["LHST", "Lord Howe Standard Time"],
  },
  {
    label: "Antarctica, Macquarie",
    value: "Antarctica/Macquarie",
    group: "UTC+11",
    offset: 11,
    keywords: ["MIST", "Macquarie Island Time"],
  },
  {
    label: "Asia, Srednekolymsk",
    value: "Asia/Srednekolymsk",
    group: "UTC+11",
    offset: 11,
    keywords: ["SRET", "Srednekolymsk Time"],
  },
  {
    label: "Pacific, Bougainville",
    value: "Pacific/Bougainville",
    group: "UTC+11",
    offset: 11,
    keywords: ["BST", "Bougainville Standard Time"],
  },
  {
    label: "Pacific, Efate",
    value: "Pacific/Efate",
    group: "UTC+11",
    offset: 11,
    keywords: ["VUT", "Vanuatu Time"],
  },
  {
    label: "Pacific, Guadalcanal",
    value: "Pacific/Guadalcanal",
    group: "UTC+11",
    offset: 11,
    keywords: ["SBT", "Solomon Islands Time"],
  },
  {
    label: "Pacific, Kosrae",
    value: "Pacific/Kosrae",
    group: "UTC+11",
    offset: 11,
    keywords: ["KOST", "Kosrae Time"],
  },
  {
    label: "Pacific, Norfolk",
    value: "Pacific/Norfolk",
    group: "UTC+11",
    offset: 11,
    keywords: ["NFT", "Norfolk Island Time"],
  },
  {
    label: "Pacific, Noumea",
    value: "Pacific/Noumea",
    group: "UTC+11",
    offset: 11,
    keywords: ["NCT", "New Caledonia Time"],
  },
  {
    label: "Pacific, Pohnpei",
    value: "Pacific/Pohnpei",
    group: "UTC+11",
    offset: 11,
    keywords: ["PONT", "Pohnpei Time"],
  },
  {
    label: "Antarctica, McMurdo",
    value: "Antarctica/McMurdo",
    group: "UTC+12",
    offset: 12,
    keywords: ["NZST", "New Zealand Standard Time"],
  },
  {
    label: "Asia, Anadyr",
    value: "Asia/Anadyr",
    group: "UTC+12",
    offset: 12,
    keywords: ["ANAT", "Anadyr Time"],
  },
  {
    label: "Asia, Kamchatka",
    value: "Asia/Kamchatka",
    group: "UTC+12",
    offset: 12,
    keywords: ["PETT", "Kamchatka Time"],
  },
  {
    label: "Pacific, Auckland",
    value: "Pacific/Auckland",
    group: "UTC+12",
    offset: 12,
    keywords: ["NZST", "New Zealand Standard Time"],
  },
  {
    label: "Pacific, Fiji",
    value: "Pacific/Fiji",
    group: "UTC+12",
    offset: 12,
    keywords: ["FJT", "Fiji Time"],
  },
  {
    label: "Pacific, Funafuti",
    value: "Pacific/Funafuti",
    group: "UTC+12",
    offset: 12,
    keywords: ["TVT", "Tuvalu Time"],
  },
  {
    label: "Pacific, Kwajalein",
    value: "Pacific/Kwajalein",
    group: "UTC+12",
    offset: 12,
    keywords: ["MHT", "Marshall Islands Time"],
  },
  {
    label: "Pacific, Majuro",
    value: "Pacific/Majuro",
    group: "UTC+12",
    offset: 12,
    keywords: ["MHT", "Marshall Islands Time"],
  },
  {
    label: "Pacific, Nauru",
    value: "Pacific/Nauru",
    group: "UTC+12",
    offset: 12,
    keywords: ["NRT", "Nauru Time"],
  },
  {
    label: "Pacific, Tarawa",
    value: "Pacific/Tarawa",
    group: "UTC+12",
    offset: 12,
    keywords: ["GILT", "Gilbert Islands Time"],
  },
  {
    label: "Pacific, Wake",
    value: "Pacific/Wake",
    group: "UTC+12",
    offset: 12,
    keywords: ["WAKT", "Wake Time"],
  },
  {
    label: "Pacific, Wallis",
    value: "Pacific/Wallis",
    group: "UTC+12",
    offset: 12,
    keywords: ["WFT", "Wallis and Futuna Time"],
  },
  {
    label: "Pacific, Chatham",
    value: "Pacific/Chatham",
    group: "UTC+12:45",
    offset: 12.75,
    keywords: ["CHAST", "Chatham Standard Time"],
  },
  {
    label: "Pacific, Apia",
    value: "Pacific/Apia",
    group: "UTC+13",
    offset: 13,
    keywords: ["WSST", "West Samoa Standard Time"],
  },
  {
    label: "Pacific, Enderbury",
    value: "Pacific/Enderbury",
    group: "UTC+13",
    offset: 13,
    keywords: ["PHOT", "Phoenix Islands Time"],
  },
  {
    label: "Pacific, Fakaofo",
    value: "Pacific/Fakaofo",
    group: "UTC+13",
    offset: 13,
    keywords: ["TKT", "Tokelau Time"],
  },
  {
    label: "Pacific, Tongatapu",
    value: "Pacific/Tongatapu",
    group: "UTC+13",
    offset: 13,
    keywords: ["TOT", "Tonga Time"],
  },
  {
    label: "Pacific, Kiritimati",
    value: "Pacific/Kiritimati",
    group: "UTC+14",
    offset: 14,
    keywords: ["LINT", "Line Islands Time"],
  },
];

export const TIMES_12 = [
  "12 AM",
  "1 AM",
  "2 AM",
  "3 AM",
  "4 AM",
  "5 AM",
  "6 AM",
  "7 AM",
  "8 AM",
  "9 AM",
  "10 AM",
  "11 AM",
  "12 PM",
  "1 PM",
  "2 PM",
  "3 PM",
  "4 PM",
  "5 PM",
  "6 PM",
  "7 PM",
  "8 PM",
  "9 PM",
  "10 PM",
  "11 PM",
];

export const TIMES_24 = [
  "00:00",
  "01:00",
  "02:00",
  "03:00",
  "04:00",
  "05:00",
  "06:00",
  "07:00",
  "08:00",
  "09:00",
  "10:00",
  "11:00",
  "12:00",
  "13:00",
  "14:00",
  "15:00",
  "16:00",
  "17:00",
  "18:00",
  "19:00",
  "20:00",
  "21:00",
  "22:00",
  "23:00",
];
